## Modelos posibles a evaluar


- Linear Regression
- Random Forest Regressor
- Gradient Boosting Regressor
- XGBoost Regressor

Los modelos serán comparados mediante MAE, RMSE y R² para seleccionar el más adecuado para la simulación del Mundial 2026.

In [1]:
import pandas as pd
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
results = pd.read_csv("data/results.csv")

#Kaggle

In [5]:
results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [6]:
results.info()

<class 'pandas.DataFrame'>
RangeIndex: 49287 entries, 0 to 49286
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49287 non-null  str
 1   home_team   49287 non-null  str
 2   away_team   49287 non-null  str
 3   home_score  49215 non-null  float64
 4   away_score  49215 non-null  float64
 5   tournament  49287 non-null  str
 6   city        49287 non-null  str
 7   country     49287 non-null  str
 8   neutral     49287 non-null  bool
dtypes: bool(1), float64(2), str(6)
memory usage: 3.1 MB

In [ ]:
ranking = pd.read_csv("data/fifa_ranking-2026-04-01.csv")

#Kaggle

In [15]:
ranking.head(20)

,Unnamed: 0,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
0,0,140.0,Brunei Darussalam,BRU,2.0,0.0,140,AFC,1992-12-31
1,1,33.0,Portugal,POR,38.0,0.0,33,UEFA,1992-12-31
2,2,32.0,Zambia,ZAM,38.0,0.0,32,CAF,1992-12-31
3,3,31.0,Greece,GRE,38.0,0.0,31,UEFA,1992-12-31
4,4,30.0,Algeria,ALG,39.0,0.0,30,CAF,1992-12-31
5,5,29.0,Yugoslavia,YUG,39.0,0.0,29,UEFA,1992-12-31
6,6,28.0,Wales,WAL,40.0,0.0,28,UEFA,1992-12-31
7,7,27.0,Côte d'Ivoire,CIV,41.0,0.0,27,CAF,1992-12-31
8,8,34.0,Austria,AUT,38.0,0.0,34,UEFA,1992-12-31
9,9,26.0,Bulgaria,BUL,41.0,0.0,26,UEFA,1992-12-31
10,10,24.0,USA,USA,43.0,0.0,24,CONCACAF,1992-12-31
11,11,23.0,Scotland,SCO,43.0,0.0,23,UEFA,1992-12-31
12,12,22.0,Cameroon,CMR,43.0,0.0,22,CAF,1992-12-31
13,13,21.0,Egypt,EGY,45.0,0.0,21,CAF,1992-12-31
14,14,20.0,Poland,POL,46.0,0.0,20,UEFA,1992-12-31
15,15,19.0,France,FRA,46.0,0.0,19,UEFA,1992-12-31
16,16,18.0,Czechoslovakia,TCH,47.0,0.0,18,UEFA,1992-12-31
17,17,25.0,Mexico,MEX,43.0,0.0,25,CONCACAF,1992-12-31
18,18,35.0,Colombia,COL,36.0,0.0,35,CONMEBOL,1992-12-31
19,19,36.0,Hungary,HUN,36.0,0.0,36,UEFA,1992-12-31

In [8]:
ranking.info()

<class 'pandas.DataFrame'>
RangeIndex: 70194 entries, 0 to 70193
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       70194 non-null  int64
 1   rank             70185 non-null  float64
 2   country_full     70194 non-null  str
 3   country_abrv     70194 non-null  str
 4   total_points     70194 non-null  float64
 5   previous_points  70194 non-null  float64
 6   rank_change      70194 non-null  int64
 7   confederation    70194 non-null  str
 8   rank_date        70194 non-null  str
dtypes: float64(3), int64(2), str(4)
memory usage: 4.8 MB

In [9]:
elo = pd.read_csv("data/eloratings.csv")

In [19]:
elo.head(70190)

            date                      team  rating  change
0     1872-11-30                   England  2003.0       3
1     1872-11-30                  Scotland  1997.0      -3
2     1873-03-08                   England  2014.0      11
3     1873-03-08                  Scotland  1986.0     -11
4     1874-03-07                   England  2006.0      -8
...          ...                       ...     ...     ...
6673  12/13/2025  Northern Mariana Islands   432.0       0
6674  12/13/2025             Cocos Islands   422.0       0
6675  12/13/2025                     Palau   402.0       0
6676  12/13/2025             Eastern Samoa   389.0       0
6677  12/13/2025                   Moldova     0.0       0

[6678 rows x 4 columns]

In [11]:
elo.info()

<class 'pandas.DataFrame'>
RangeIndex: 6678 entries, 0 to 6677
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    6678 non-null   str
 1   team    6678 non-null   str
 2   rating  6647 non-null   float64
 3   change  6678 non-null   int64
dtypes: float64(1), int64(1), str(2)
memory usage: 208.8 KB

In [ ]:
elo_actual = pd.read_csv("data/elo_selecciones_ocr.csv")


# https://www.eloratings.net/

In [17]:
elo_actual.head()

   rank              team   elo
0     1            España  2165
1     2  Argentina 23 | 5  1987
2     4          Ingatema  2020
3     5            Brasil  1988
4     6          Portugal  1984

In [14]:
elo_actual.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   rank    120 non-null    int64
 1   team    120 non-null    str
 2   elo     120 non-null    int64
dtypes: int64(2), str(1)
memory usage: 2.9 KB